--- 
apiVersion: v1
kind: Secret
metadata: 
  name: mongodb-secret
  namespace: default
  resourceVersion: "164619"
  uid: cfee02d6-c137-11e5-8d73-42010af00002
type: Opaque
data: 
  mongo-root-username:  dXNlcm5hbWU= 
  mongo-root-password:  cGFzc3dvcmQ=

